spring:
  datasource:
    username: rocketleagueserver
    password: rocketleagueserver
    url: jdbc:mysql://localhost:3306/rocketleagueserver #connects to mySQL
    
    # JPA properties
  jpa:
    hibernate: #takes entities and converts them to SQL statements
      ddl-auto: update # CHANGE TO UPDATE AFTER ENTITIES ARE CORRECT > update otherwise
    show-sql: true
    defer-datasource-initialization: true #when spring boot is inserting into tables, spring boot can sometimes insert data before tables are created, this tells spring to wait
    
  sql:
    init:
      mode: never # never otherwise