INSERT INTO car (car_body_name) VALUES ('Masamune');
INSERT INTO car (car_body_name) VALUES ('Octane');
INSERT INTO car (car_body_name) VALUES ('Scarab');
INSERT INTO car (car_body_name) VALUES ('Takumi');
INSERT INTO car (car_body_name) VALUES ('Aftershock');
INSERT INTO car (car_body_name) VALUES ('Ripper');
INSERT INTO car (car_body_name) VALUES ('Zippy');
INSERT INTO car (car_body_name) VALUES ('Dominus');
INSERT INTO car (car_body_name) VALUES ('Peregrine GT');
INSERT INTO car (car_body_name) VALUES ('Road Hog');
INSERT INTO car (car_body_name) VALUES ('Breakout');
INSERT INTO car (car_body_name) VALUES ('Aston Martin');
INSERT INTO car (car_body_name) VALUES ('Dingo');
INSERT INTO car (car_body_name) VALUES ('Van');
